---
image:
  repo: "localhost:5001"
  tag: latest
  pullPolicy: Always

app:
  name: component-inventory
  serviceName: inventory-api
  configPath: /etc/cis
  livenessURI: /_health/liveness
  containerPort: 8020

fleetdb:
  env:
    endpoint: http://fleetdb:8000
    disable_oauth: true
    audience_endpoint: "placeholder"
    issuer_endpoint: "placeholder"
    client_id: "placeholder"
    client_scopes:
      - "placeholder"
